#!/usr/bin/awk -f
BEGIN {
	FS=",";
	OFS=",";
	count = 0;
}
{
    number = int(rand()*800);
    number = number*100;
    if (number == 0) {number = 7000;}
    #print number;
    print $1,$2,$3,$4,$5,$6,number,$7;
	
}
